class Conf:
    # String generator will run every GENERATOR_INTERVAL seconds
    GENERATOR_INTERVAL = 10

    # Results will be monitored every SEARCH_INTERVAL seconds
    SEARCH_INTERVAL = 30

    # Length of data (in terms of number of words) generated by
    # the data generator at once
    SEQUENCE_LENGTH = 40

    # Length of strings (in terms of number of characters) generated by
    # the string generator
    STRING_LENGTHS = [2, 3, 4, 5, 6, 7, 8]

    # These are the files where the generator will dump the data
    DATA_DIRECTORY = 'Data'
    DATA_FILE_ONE = 'data_one.txt'
    DATA_FILE_TWO = 'data_two.txt'

    # Search results will be logged to this file
    RESULTS_DIRECTORY = 'Logs'
    RESULTS_FILE = 'search_results.log'

    # String generator will have 50% probably of generating this keyword
    DATA_CRITICAL_KEYWORD = 'CDS'

    # String generator will have 50% probably of generating this keyword
    SEARCH_CRITICAL_KEYWORD = 'CDS'
